---
title: "bars_vs_topbars"
output: html_document
---

```{r setup}
devtools::load_all()
library(patchwork)

data.frame(x=(1:50)/10, y=(sin((1:50)/10)*15+15)) %>% ggplot(aes(x,y)) + geom_line() + geom_point(na.rm=T) ->p
```



# topbars work without ggsweeps
```{r}
mystyle<-ggsweeps.defaultstyle
mystyle$height=0.03
p | 
  p +  
   geom_topbar(0,1, label=" topbar on bare ggplot", label.position = "right", label.size = 3, style=mystyle) +
   geom_topbar(4,5, line=2.5, label=" automatically takes space ", label.position = "left", label.size = 3, label.col = "blue", fill="skyblue", style=mystyle) 

```

# label.x .y
```{r}
  p + geom_topbar(0,1, label=" label", label.x = 3, label.y=20) 
  p + geom_topbar(0,1, label=" label", label.x = 3, label.y=I(.9)) 

```
# label.hjust vjust
```{r}
  p + geom_topbar(0,1, label=" label", get_data=function(y)y*5)

```

# lines.to
```{r}
.get_data <-function(df){
  #print(df)
  df
}
  p +  
    geom_topbar(4,5, line=2.5, 
                get_data = .get_data,
                label=" lines to ", label.position = "left", label.size = 3, label.col = "blue", 
                fill="blue", 
                style=mystyle,
                line_to.y = "data",
                line_to.y2 = "data",
                line_to.size = .1, line_to.linetype = 3, line_to.arrow = arrow(type = "closed", length=unit(2,"mm")),
                line_to.gap=2
    )

```
